# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=150)),
                ('abstract', models.CharField(max_length=250)),
                ('mentor_name', models.CharField(max_length=150)),
                ('amt', models.IntegerField()),
                ('fund_approved', models.CharField(max_length=150)),
                ('stage', models.IntegerField()),
            ],
        ),
    ]
