# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mentor_name',
        ),
        migrations.AddField(
            model_name='student',
            name='t_id',
            field=models.IntegerField(default=0),
        ),
    ]
