# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_student_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='abstract',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='amt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fund_approved',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
