# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20160928_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='t_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
