# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='t_id',
        ),
    ]
