# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_student_t_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='t_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
