# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=4, null=True),
        ),
    ]
