# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_student_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student3',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
