# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20161006_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='g_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
