# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_student_g_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rej',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
