# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_student_rej'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
